channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - r-base=4.0.3
  - r-readr=1.4.0
  - r-tibble=3.1.3
  - r-dplyr=1.0.6
  - r-tidyr=1.1.3
  - r-ggplot2=3.3.4
  - r-writexl=1.4.0
  - bioconductor-deseq2=1.30.1
